name: Deploy Group Games

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (for the frontend build, if needed)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Ensure compatibility with your static app's build tools
    
    # Step 3: Install dependencies and build the static web app
    - name: Build static web app
      run: |
        cd app/static
        npm install
        npm run build

    # Step 4: Deploy to Azure Static Web Apps
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "app/static"        # Location of the static assets
        api_location: "app"              # Location of the FastAPI backend
        output_location: "app/static/build" # Output folder of the static web app
        deployment_action: "upload"        # Correct value for deployment_action
