name: Deploy Group Games

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Deploy to Azure
      run: |
        az deployment group create           --resource-group GroupGamesResources           --template-file infrastructure/main.bicep           --parameters @infrastructure/parameters.json